# Generated by Django 5.2.5 on 2025-09-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('BOLOS', 'Bolos'), ('TORTAS', 'Tortas'), ('CARNES', 'Carnes'), ('SALADAS', 'Saladas'), ('SOPAS', 'Sopas')], default='', max_length=100),
        ),
    ]
